name: release

on:
  push:
    branches:
      - "*"

jobs:
  release:
    timeout-minutes: 720
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 10
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build and test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        id: install-r
        with:
          bioc-version: release
      - name: Install scRepertoire from Bioconductor
        run: |
          Rscript -e 'if (!requireNamespace("BiocManager", quietly=TRUE)) install.packages("BiocManager")'
          Rscript -e 'BiocManager::install("scRepertoire", ask=FALSE, update=FALSE)'
